version: '3.5'

networks:
        inception:
                name: inception

volumes:
        db:
                driver_opts:
                        type: none
                        o: bind
                        device: /home/ccardozo/data/mariadb
        wp:
                driver_opts:
                        type: none
                        o: bind
                        device: /home/ccardozo/data/wordpress

services:
        nginx:
                build: requirements/nginx
                image: nginx
                container_name: nginx
                restart: unless-stopped
                depends_on:
                        - wordpress
                networks:
                        - inception
                ports:
                        - 443:443
                volumes:
                        - wp:/var/www/wordpress

        mariadb:
                container_name: mariadb
                image: mariadb
                build: 
                        context: requirements/mariadb
                        args:
                                DB_NAME: ${DB_NAME}
                                DB_LOGIN: ${DB_LOGIN}
                                DB_PASS: ${DB_PASS}
                                DB_ROOT_LOGIN: ${DB_ROOT_LOGIN}
                                DB_ROOT_PASS: ${DB_ROOT_PASS}
                restart: unless-stopped
                networks:
                        - inception
                volumes:
                        - db:/var/lib/mysql

                
        wordpress:
                container_name: wordpress
                image: wordpress
                build: requirements/wordpress
                restart: unless-stopped
                networks:
                        - inception
                depends_on:
                        - mariadb
                volumes:
                        - wp:/var/www/wordpress
                env_file:
                        - .env
               



